SHOW DATABASES;
CREATE DATABASE `moonbuggy` /*!40100 COLLATE  utf8_bin  */;
SHOW DATABASES;
USE `moonbuggy`;
/*SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`= moonbuggy ;
SHOW TABLE STATUS FROM `moonbuggy`;
SHOW FUNCTION STATUS WHERE `Db`= moonbuggy ;
SHOW PROCEDURE STATUS WHERE `Db`= moonbuggy ;
SHOW TRIGGERS FROM `moonbuggy`;
SELECT *, EVENT_SCHEMA AS `Db`, EVENT_NAME AS `Name` FROM information_schema.`EVENTS` WHERE `EVENT_SCHEMA`= moonbuggy ;
SHOW VARIABLES LIKE  collation_server ;
SHOW CREATE DATABASE `moonbuggy`;
SHOW VARIABLES LIKE  collation_database ;*/
CREATE TABLE buggy (
	 id INT(11) UNSIGNED AUTO_INCREMENT,
	 fecha DATETIME,
	 vibracionIS  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 vibracionDS  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 vibracionII  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 vibrazionDI  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 temperatura  FLOAT NOT NULL DEFAULT  0 ,
	 humedad  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 coord_gps  FLOAT NOT NULL DEFAULT  0 ,
	 bateria  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 senal  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 tensionIS  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 tensionDS  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 tensionII  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	 tensionDI  FLOAT UNSIGNED NOT NULL DEFAULT  0 ,
	PRIMARY KEY (`id`)
)
COLLATE= utf8_bin
;
/*SELECT `DEFAULT_COLLATION_NAME` FROM `information_schema`.`SCHEMATA` WHERE `SCHEMA_NAME`= moonbuggy ;
SHOW TABLE STATUS FROM `moonbuggy`;
SHOW FUNCTION STATUS WHERE `Db`= moonbuggy ;
SHOW PROCEDURE STATUS WHERE `Db`= moonbuggy ;
SHOW TRIGGERS FROM `moonbuggy`;
SHOW CREATE TABLE `moonbuggy`.`buggy1`;*/
